In [13]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

In [14]:
dataset = pd.read_csv("/home/madhav/Desktop/MADHAV/finaldata.csv")

In [15]:
dataset.head(5)

state  account length  area code phone number international plan  \
0    KS             128        415     382-4657                 no   
1    OH             107        415     371-7191                 no   
2    OK              75        415     330-6626                yes   
3    IA             168        408     363-1107                 no   
4    MT              95        510     394-8006                 no   

  voice mail plan  number vmail messages  total day minutes  total day calls  \
0             yes                     25              265.1              110   
1             yes                     26              161.6              123   
2              no                      0              166.7              113   
3              no                      0              128.8               96   
4              no                      0              156.6               88   

   total day charge  ...    total eve calls  total eve charge  \
0             45.07  ...                 99             16.78   
1             27.47  ...                103             16.62   
2             28.34  ...                122             12.61   
3             21.90  ...                 71              8.92   
4             26.62  ...                 75             21.05   

   total night minutes  total night calls  total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                186.9                121                8.41   
3                141.1                128                6.35   
4                192.3                115                8.65   

   total intl minutes  total intl calls  total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                10.1                 3               2.73   
3                11.2                 2               3.02   
4                12.3                 5               3.32   

   customer service calls  churn  
0                       1  False  
1                       1  False  
2                       3  False  
3                       1  False  
4                       3  False  

[5 rows x 21 columns]

In [16]:
dataset['international plan'] = np.where(dataset['international plan']=='Yes', 1,0)
dataset['voice mail plan'] = np.where(dataset['voice mail plan']=='Yes', 1,0)
dataset['churn'] = np.where(dataset['churn']==True, 1,0)
dataset = dataset.drop(['state','phone number','area code'], axis=1)

X = dataset.drop('churn', axis=1)  # X is called attributes
y = dataset['churn'] # Y is called label

In [17]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30) 

In [18]:
# Training
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [19]:
#Predictions
y_pred = classifier.predict(X_test)

In [20]:
y_pred


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,

In [21]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

# We can see that out of 1000 test cases our algorithm has misclassified 72+68 = 140 . We have 86% accuracy.

[[545  43]
 [ 42  27]]
             precision    recall  f1-score   support

          0       0.93      0.93      0.93       588
          1       0.39      0.39      0.39        69

avg / total       0.87      0.87      0.87       657



In [10]:
# Link
# https://stackabuse.com/decision-trees-in-python-with-scikit-learn/

In [22]:
from sklearn.svm import SVC 

clf = SVC(kernel='linear', C= 1)
clf.fit(X,y)
prediction = clf.predict(X_test)


from sklearn.metrics import precision_score,recall_score, confusion_matrix, classification_report,accuracy_score, f1_score

print('Accuracy:', accuracy_score(y_test, y_pred))
print('F1 score:', f1_score(y_test , y_pred ))
print('Recall:', recall_score(y_test,  y_pred))
print('Precision:', precision_score(y_test,  y_pred))
print('\n clasification report:\n', classification_report(y_test, y_pred))
print('\n confussion matrix:\n',confusion_matrix(y_test,  y_pred))

Accuracy: 0.8706240487062404
F1 score: 0.38848920863309355
Recall: 0.391304347826087
Precision: 0.38571428571428573

 clasification report:
              precision    recall  f1-score   support

          0       0.93      0.93      0.93       588
          1       0.39      0.39      0.39        69

avg / total       0.87      0.87      0.87       657


 confussion matrix:
 [[545  43]
 [ 42  27]]
