In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
#from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
#from sklearn.cross_validation import train_test_split
import seaborn as sns
#import dataset 
from statistics import mode


In [2]:
# Data Import
train_data = pd.read_csv("/home/madhav/Desktop/WNS_Competition/train_LZdllcl.csv")

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
employee_id             54808 non-null int64
department              54808 non-null object
region                  54808 non-null object
education               52399 non-null float64
gender                  54808 non-null object
recruitment_channel     54808 non-null object
no_of_trainings         54808 non-null int64
age                     54808 non-null int64
previous_year_rating    50684 non-null float64
length_of_service       54808 non-null int64
KPIs_met >80%           54808 non-null int64
awards_won?             54808 non-null int64
avg_training_score      54808 non-null int64
is_promoted             54808 non-null int64
dtypes: float64(2), int64(8), object(4)
memory usage: 5.9+ MB


In [4]:
train_data.shape

(54808, 14)

In [44]:
(train_data['is_promoted']).value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [45]:
NOT_PROMOTED=50140*100/54808
PROMOTED    =

In [46]:
train_data['is_promoted'].value_counts()/np.sum(train_data['is_promoted'].value_counts().values)*100

0    91.482995
1     8.517005
Name: is_promoted, dtype: float64

In [5]:
train_data['department'].unique()

array(['Sales & Marketing', 'Operations', 'Technology', 'Analytics',
       'R&D', 'Procurement', 'Finance', 'HR', 'Legal'], dtype=object)

In [6]:
train_data['region'].unique()

array(['region_7', 'region_22', 'region_19', 'region_23', 'region_26',
       'region_2', 'region_20', 'region_34', 'region_1', 'region_4',
       'region_29', 'region_31', 'region_15', 'region_14', 'region_11',
       'region_5', 'region_28', 'region_17', 'region_13', 'region_16',
       'region_25', 'region_10', 'region_27', 'region_30', 'region_12',
       'region_21', 'region_8', 'region_32', 'region_6', 'region_33',
       'region_24', 'region_3', 'region_9', 'region_18'], dtype=object)

In [7]:
train_data['education'].unique()

array([ 3.,  2., nan,  1.])

In [8]:
train_data.groupby(['education']).count()

employee_id  department  region  gender  recruitment_channel  \
education                                                                 
1.0                805         805     805     805                  805   
2.0              36669       36669   36669   36669                36669   
3.0              14925       14925   14925   14925                14925   

           no_of_trainings    age  previous_year_rating  length_of_service  \
education                                                                    
1.0                    805    805                   458                805   
2.0                  36669  36669                 33404              36669   
3.0                  14925  14925                 14798              14925   

           KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
education                                                               
1.0                  805          805                 805          805  
2.0                36669        36669               36669        36669  
3.0                14925        14925               14925        14925

In [9]:
(train_data['education']==2).value_counts()

True     36669
False    18139
Name: education, dtype: int64

In [10]:
train_data['gender'].unique()

array(['f', 'm'], dtype=object)

In [11]:
train_data['recruitment_channel'].unique()

array(['sourcing', 'other', 'referred'], dtype=object)

In [12]:
train_data['no_of_trainings'].unique()

array([ 1,  2,  3,  4,  7,  5,  6,  8, 10,  9])

In [13]:
train_data['age'].unique()

array([35, 30, 34, 39, 45, 31, 33, 28, 32, 49, 37, 38, 41, 27, 29, 26, 24,
       57, 40, 42, 23, 59, 44, 50, 56, 20, 25, 47, 36, 46, 60, 43, 22, 54,
       58, 48, 53, 55, 51, 52, 21])

In [14]:
train_data['previous_year_rating'].unique()

array([ 5.,  3.,  1.,  4., nan,  2.])

In [15]:
train_data.groupby(['previous_year_rating']).count()

employee_id  department  region  education  gender  \
previous_year_rating                                                       
1.0                          6223        6223    6223       5887    6223   
2.0                          4225        4225    4225       4035    4225   
3.0                         18618       18618   18618      17867   18618   
4.0                          9877        9877    9877       9509    9877   
5.0                         11741       11741   11741      11362   11741   

                      recruitment_channel  no_of_trainings    age  \
previous_year_rating                                                
1.0                                  6223             6223   6223   
2.0                                  4225             4225   4225   
3.0                                 18618            18618  18618   
4.0                                  9877             9877   9877   
5.0                                 11741            11741  11741   

                      length_of_service  KPIs_met >80%  awards_won?  \
previous_year_rating                                                  
1.0                                6223           6223         6223   
2.0                                4225           4225         4225   
3.0                               18618          18618        18618   
4.0                                9877           9877         9877   
5.0                               11741          11741        11741   

                      avg_training_score  is_promoted  
previous_year_rating                                   
1.0                                 6223         6223  
2.0                                 4225         4225  
3.0                                18618        18618  
4.0                                 9877         9877  
5.0                                11741        11741

In [16]:
train_data['length_of_service'].unique()

array([ 8,  4,  7, 10,  2,  5,  6,  1,  3, 16,  9, 11, 26, 12, 17, 14, 13,
       19, 15, 23, 18, 20, 22, 25, 28, 24, 31, 21, 29, 30, 34, 27, 33, 32,
       37])

In [17]:
train_data['KPIs_met >80%'].unique()

array([1, 0])

In [18]:
train_data['awards_won?'].unique()

array([0, 1])

In [19]:
train_data['avg_training_score'].unique()

array([49, 60, 50, 73, 85, 59, 63, 83, 54, 77, 80, 84, 51, 46, 75, 57, 70,
       68, 79, 44, 72, 61, 48, 58, 87, 47, 52, 88, 71, 65, 62, 53, 78, 91,
       82, 69, 55, 74, 86, 90, 92, 67, 89, 56, 76, 81, 45, 64, 39, 94, 93,
       66, 95, 42, 96, 40, 99, 43, 97, 41, 98])

In [20]:
train_data['is_promoted'].unique()

array([0, 1])

In [21]:
################### Calculation of missing values in the data ###########################

(train_data[train_data.apply(lambda x: x.count(), axis=1)< 14]).count# 6148 rows have missing values

<bound method DataFrame.count of        employee_id         department     region  education gender  \
10           29934         Technology  region_23        NaN      m   
21           33332         Operations  region_15        NaN      m   
23           71177        Procurement   region_5        2.0      m   
29           74759  Sales & Marketing   region_4        2.0      m   
32           35465  Sales & Marketing   region_7        NaN      f   
43           17423  Sales & Marketing   region_2        NaN      m   
56           45709  Sales & Marketing  region_31        2.0      f   
58           26599  Sales & Marketing  region_16        2.0      m   
62            9150          Analytics  region_22        2.0      f   
66           77981            Finance  region_22        2.0      m   
67           16502  Sales & Marketing  region_22        2.0      m   
82           66013  Sales & Marketing   region_2        NaN      m   
84           44575              Legal   region_7        2

In [22]:
len(train_data.columns)

14

In [23]:
train_data.isnull().sum(axis=0)

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [25]:
data=train_data.dropna()

In [26]:
data.isnull().sum(axis=0)

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [27]:
data.head(5)

employee_id         department     region  education gender  \
0        65438  Sales & Marketing   region_7        3.0      f   
1        65141         Operations  region_22        2.0      m   
2         7513  Sales & Marketing  region_19        2.0      m   
3         2542  Sales & Marketing  region_23        2.0      m   
4        48945         Technology  region_26        2.0      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [33]:
data=data.drop(data.columns[[0,1,2,4,5]],axis=1)

In [34]:
data.head(5)

education  no_of_trainings  age  previous_year_rating  length_of_service  \
0        3.0                1   35                   5.0                  8   
1        2.0                1   30                   5.0                  4   
2        2.0                1   34                   3.0                  7   
3        2.0                2   39                   1.0                 10   
4        2.0                1   45                   3.0                  2   

   KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
0              1            0                  49            0  
1              0            0                  60            0  
2              0            0                  50            0  
3              0            0                  50            0  
4              0            0                  73            0

In [47]:
data['is_promoted'].value_counts()/np.sum(data['is_promoted'].value_counts().values)*100

## This is the case of class imbalance

0    91.302918
1     8.697082
Name: is_promoted, dtype: float64